### ISSUE TITLE
执行 biz -i 报错

### ISSUE THREAD

**Issue by AmarisEx** [sofastack-guides/sofa-ark-spring-guides#11]
java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
	at org.springframework.util.Assert.notEmpty(Assert.java:470) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180) ~[spring-boot-autoconfigure-2.6.6.jar:2.6.6]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123) ~[spring-boot-autoconfigure-2.6.6.jar:2.6.6]
	at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434) ~[spring-boot-autoconfigure-2.6.6.jar:2.6.6]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:879) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) ~[spring-context-5.3.18.jar:5.3.18]

**Comment by lvjing2** [comment]
麻烦拉下最新的代码，问题已经修复了。

**Comment by lvjing2** [comment]
该 issue 长时间无回复，暂时关闭，有需要可以再开启
