### ISSUE TITLE
biz -i安装报错

### ISSUE THREAD

**Issue by zzy-design** [sofastack-guides/sofa-ark-spring-guides#35]
java.lang.IllegalStateException: Error processing condition on com.alipay.sofa.serverless.plugin.BaseRuntimeAutoConfiguration.arkAutowiredBeanPostProcessor
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:193) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:153) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:129) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:343) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:748) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.16.jar:2.7.16]
	at com.alipay.sofa.springbootarkbiz.SpringBootArkBizApplication.main(SpringBootArkBizApplication.java:23) ~[null-null-20231017230358176-unpack/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_301]
	at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) ~[sofa-ark-archive-2.2.4-20230927.035559-1.jar:?]
	at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:292) ~[sofa-ark-container-2.2.4-20230927.035549-1.jar:?]
	at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:168) ~[sofa-ark-api-2.2.4-20230927.035521-1.jar:?]
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:343) ~[sofa-ark-api-2.2.4-20230927.035521-1.jar:?]
	at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:328) ~[sofa-ark-api-2.2.4-20230927.035521-1.jar:?]
	at com.alipay.sofa.ark.container.service.biz.BizCommandProvider$BizCommand$1.run(BizCommandProvider.java:249) ~[sofa-ark-container-2.2.4-20230927.035549-1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_301]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_301]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_301]
Caused by: java.lang.IllegalStateException: @ConditionalOnMissingBean did not specify a bean using type, name or annotation and the attempt to deduce the bean's type failed
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.validate(OnBeanCondition.java:490) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.<init>(OnBeanCondition.java:439) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:155) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	... 28 more
Caused by: org.springframework.boot.autoconfigure.condition.OnBeanCondition$BeanTypeDeductionException: Failed to deduce bean type for com.alipay.sofa.serverless.plugin.BaseRuntimeAutoConfiguration.arkAutowiredBeanPostProcessor
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.deducedBeanTypeForBeanMethod(OnBeanCondition.java:520) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.deducedBeanType(OnBeanCondition.java:509) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition$Spec.<init>(OnBeanCondition.java:432) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:155) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.7.16.jar:2.7.16]
	... 28 more
Caused by: com.alipay.sofa.ark.exception.ArkLoaderException: [ArkBiz Loader] spring-boot-ark-biz:0.0.1-SNAPSHOT : can not load class: com.alipay.sofa.serverless.common.service.ArkAutowiredBeanPostProcessor

**Comment by lvjing2** [comment]
项目已迁移，请看最新samples 用例
