### ISSUE TITLE
执行biz -i失败

### ISSUE THREAD

**Issue by budong90** [sofastack-guides/sofa-ark-spring-guides#8]
2022-05-20 11:16:09.544 ERROR 87482 --- [et-command-1-T3] o.s.boot.SpringApplication               : Application run failed

java.lang.RuntimeException: Meet exception when determine whether to start SOFAArk!
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:66) ~[sofa-ark-springboot-starter-2.0.0.jar:na]
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:40) ~[sofa-ark-springboot-starter-2.0.0.jar:na]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.7.jar:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.7.jar:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.7.jar:5.3.7]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.7.jar:5.3.7]
        at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82) ~[spring-boot-2.5.0.jar:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63) ~[spring-boot-2.5.0.jar:2.5.0]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[na:1.8.0_291]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.5.0.jar:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.5.0.jar:2.5.0]
        at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62) ~[spring-boot-2.5.0.jar:2.5.0]
        at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:373) [spring-boot-2.5.0.jar:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) [spring-boot-2.5.0.jar:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1336) [spring-boot-2.5.0.jar:2.5.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1325) [spring-boot-2.5.0.jar:2.5.0]
        at com.alipay.sofa.springbootarkbiz.SpringBootArkBizApplication.main(SpringBootArkBizApplication.java:19) [null-null-20220520111608511-unpack/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_291]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_291]
        at com.alipay.sofa.ark.bootstrap.MainMethodRunner.run(MainMethodRunner.java:48) [sofa-ark-archive-2.0.0.jar!/:na]
        at com.alipay.sofa.ark.container.model.BizModel.start(BizModel.java:277) [sofa-ark-container-2.0.0.jar!/:na]
        at com.alipay.sofa.ark.api.ArkClient.installBiz(ArkClient.java:172) [sofa-ark-api-2.0.0.jar!/:na]
        at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:348) [sofa-ark-api-2.0.0.jar!/:na]
        at com.alipay.sofa.ark.api.ArkClient.installOperation(ArkClient.java:333) [sofa-ark-api-2.0.0.jar!/:na]
        at com.alipay.sofa.ark.container.service.biz.BizCommandProvider$BizCommand$1.run(BizCommandProvider.java:249) [sofa-ark-container-2.0.0.jar!/:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_291]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_291]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_291]
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.alipay.sofa.ark.support.startup.EmbedSofaArkBootstrap.launch(EmbedSofaArkBootstrap.java:60) ~[sofa-ark-support-starter-2.0.0.jar:na]
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.startUpArkEmbed(ArkApplicationStartListener.java:90) ~[sofa-ark-springboot-starter-2.0.0.jar:na]
        at com.alipay.sofa.ark.springboot.listener.ArkApplicationStartListener.onApplicationEvent(ArkApplicationStartListener.java:53) ~[sofa-ark-springboot-starter-2.0.0.jar:na]
        ... 29 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.createContainerClassLoader(AbstractLauncher.java:139) ~[sofa-ark-archive-2.0.0.jar:na]
        at com.alipay.sofa.ark.bootstrap.AbstractLauncher.launch(AbstractLauncher.java:64) ~[sofa-ark-archive-2.0.0.jar:na]
        at com.alipay.sofa.ark.support.startup.EmbedSofaArkBootstrap.launch(EmbedSofaArkBootstrap.java:58) ~[sofa-ark-support-starter-2.0.0.jar:na]
        ... 31 common frames omitted

**Comment by lvjing2** [comment]
麻烦拉最新的代码试下

**Comment by lvjing2** [comment]
暂时关闭，有需要可以再开启
